default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV["DATABASE_HOST"] || '127.0.0.1' %>
  port: <%= ENV["DATABASE_PORT"] || '5432' %>
  username: <%= ENV["DATABASE_USER"] || 'root' %>
  password: <%= ENV["DATABASE_PASS"] || 'root' %>

development:
  <<: *default
  database: my_taxi_development

test:
  <<: *default
  database: my_taxi_test

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>
